/*
 Anwendungskontext: Brauerei
 Gruppenmitglieder [Vorname, Nachname, Matrikelnummer]:
 - Jan, Schulze, 7217725
 - Jonas, Goldbach, 7217641
 */

-- ====================================================================================
-- DROP SYNTAX
-- ====================================================================================


-- ----> DROP OPTION 1 (Löscht alles was es gibt, erzeugt keine Fehler) - Aus dem Internet.
-- ----> Quelle: https://stackoverflow.com/questions/1690404/how-to-drop-all-user-tables

/*
BEGIN
    FOR cur_rec IN (SELECT object_name, object_type
                    FROM user_objects
                    WHERE object_type IN
                          ('TABLE',
                           'VIEW',
                           'MATERIALIZED VIEW',
                           'PACKAGE',
                           'PROCEDURE',
                           'FUNCTION',
                           'SEQUENCE',
                           'SYNONYM',
                           'PACKAGE BODY',
                           'INDEX'
                              ))
        LOOP
            BEGIN
                IF cur_rec.object_type = 'TABLE'
                THEN
                    EXECUTE IMMEDIATE 'DROP '
                        || cur_rec.object_type
                        || ' "'
                        || cur_rec.object_name
                        || '" CASCADE CONSTRAINTS';
                ELSE
                    EXECUTE IMMEDIATE 'DROP '
                        || cur_rec.object_type
                        || ' "'
                        || cur_rec.object_name
                        || '"';
                END IF;
            EXCEPTION
                WHEN OTHERS
                    THEN
                        DBMS_OUTPUT.put_line ('FAILED: DROP '
                            || cur_rec.object_type
                            || ' "'
                            || cur_rec.object_name
                            || '"'
                        );
            END;
        END LOOP;
    FOR cur_rec IN (SELECT *
                    FROM all_synonyms
                    WHERE table_owner IN (SELECT USER FROM dual))
        LOOP
            BEGIN
                EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM ' || cur_rec.synonym_name;
            END;
        END LOOP;
END;
/
*/

-- ----> DROP OPTION 2 (Erzeugt Fehler, bei erster Ausführung) - Selbst programmiert


DROP TABLE BIERSORTE_ZUTAT CASCADE CONSTRAINTS;
DROP TABLE ZUTAT CASCADE CONSTRAINTS;
DROP TABLE LAGERBESTAND_LAGERABSCHNITT CASCADE CONSTRAINTS;
DROP TABLE LAGERABSCHNITT CASCADE CONSTRAINTS;
DROP TABLE LAGERBESTAND CASCADE CONSTRAINTS;
DROP TABLE LAGER CASCADE CONSTRAINTS;
DROP TABLE LAGERBEDINGUNG CASCADE CONSTRAINTS;
DROP TABLE VERPACKUNG CASCADE CONSTRAINTS;
DROP TABLE BEHAELTER CASCADE CONSTRAINTS;
DROP TABLE STANDORT CASCADE CONSTRAINTS;
DROP TABLE BIERSORTE CASCADE CONSTRAINTS;


-- ----> DROP OPTION 3 (Zeigt die Befehle nur an, führt aber nicht aus) - Aus dem Internet
-- ----> Quelle: https://stackoverflow.com/questions/1690404/how-to-drop-all-user-tables

-- select 'drop table '||table_name||' cascade constraints;' from user_tables;

-- ====================================================================================
-- ERSTELLUNG DER TABELLEN
-- ====================================================================================


CREATE TABLE BIERSORTE
(
    BIERSORTE_ID   INTEGER,
    BIERSORTE_NAME           VARCHAR2(20) NOT NULL,
    MARKE          VARCHAR2(20),
    ALKOHOLGEHALT  NUMBER(6, 4),
    MIN_TEMPERATUR NUMBER(6, 4),
    MAX_TEMPERATUR NUMBER(6, 4),
    PRIMARY KEY (BIERSORTE_ID),
    CONSTRAINT POSITIVE_NUMBER_CHECK CHECK (ALKOHOLGEHALT >= 0)
);

CREATE TABLE STANDORT
(
    STANDORT_ID INTEGER,
    PLZ         VARCHAR2(5),
    ORT         VARCHAR2(20),
    STRASSE     VARCHAR2(20),
    HAUSNUMMER  CHAR(5),
    GEBAUDE     VARCHAR2(20),
    RAUM        NUMBER(3, 0),
    PRIMARY KEY (STANDORT_ID),
    CONSTRAINT PRUEFE_PLZ CHECK (LENGTH(PLZ) = 5 AND REGEXP_LIKE(PLZ, '^[0-9]+$'))
);

CREATE TABLE BEHAELTER
(
    BEHAELTER_ID INTEGER,
    BIERSORTE_ID INTEGER,
    BEHAELTERTYP VARCHAR2(20),
    MATERIAL     VARCHAR2(50),
    FUELLMENGE   NUMBER(15, 3),
    KAPAZITAET NUMBER(15, 3),
    ABFUELLDATUM DATE,
    PRIMARY KEY (BEHAELTER_ID),
    FOREIGN KEY (BIERSORTE_ID) REFERENCES BIERSORTE (BIERSORTE_ID),
    CONSTRAINT FUELLMENGE_CHECK CHECK (FUELLMENGE <= KAPAZITAET)
);

CREATE TABLE VERPACKUNG
(
    VERPACKUNG_ID     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    SUB_VERPACKUNG_ID INTEGER,
    VERPACKUNG_NAME              VARCHAR2(20),
    ANZAHL_EINHEITEN  INTEGER,
    PRIMARY KEY (VERPACKUNG_ID),
    FOREIGN KEY (SUB_VERPACKUNG_ID) REFERENCES VERPACKUNG (VERPACKUNG_ID)
);

CREATE TABLE LAGERBEDINGUNG
(
    LAGERBEDINGUNG_ID INTEGER,
    TEMPERATUR        NUMBER(6, 4),
    LUFTFEUCHTIGKEIT  NUMBER(6, 5),
    PRIMARY KEY (LAGERBEDINGUNG_ID),
    CONSTRAINT LUFTFEUCHTIGKEIT_PROZENT_CHECK CHECK (LUFTFEUCHTIGKEIT >= 0 AND LUFTFEUCHTIGKEIT <= 0.2),
    CONSTRAINT TEMPERATUR_CHECK CHECK (TEMPERATUR >= 4 AND TEMPERATUR <= 15)
);

CREATE TABLE LAGER
(
    LAGER_ID    INTEGER,
    STANDORT_ID INTEGER,
    GROESSE     NUMBER(10, 2),
    PRIMARY KEY (LAGER_ID),
    FOREIGN KEY (STANDORT_ID) REFERENCES STANDORT (STANDORT_ID),
    CONSTRAINT LAGERGROESSE_CHECK CHECK (GROESSE >= 100)
);

CREATE TABLE LAGERBESTAND
(
    LAGERBESTAND_ID  INTEGER,
    BEHAELTER_ID     INTEGER NOT NULL,
    VERPACKUNG_ID    INTEGER NOT NULL,
    PRIMARY KEY (LAGERBESTAND_ID),
    FOREIGN KEY (BEHAELTER_ID) REFERENCES BEHAELTER (BEHAELTER_ID),
    FOREIGN KEY (VERPACKUNG_ID) REFERENCES VERPACKUNG (VERPACKUNG_ID)
);

CREATE TABLE LAGERABSCHNITT
(
    LAGERABSCHNITT_ID INTEGER,
    LAGERBEDINGUNG_ID INTEGER,
    LAGER_ID          INTEGER,
    GROESSE           NUMBER(8, 2),
    PRIMARY KEY (LAGERABSCHNITT_ID),
    FOREIGN KEY (LAGER_ID) REFERENCES LAGER (LAGER_ID),
    FOREIGN KEY (LAGERBEDINGUNG_ID) REFERENCES LAGERBEDINGUNG (LAGERBEDINGUNG_ID),
    CONSTRAINT LAGERABSCHNITTGROESSE_CHECK CHECK (GROESSE > 0)
);

CREATE TABLE LAGERBESTAND_LAGERABSCHNITT
(
    LAGERBESTAND_ID   INTEGER,
    LAGERABSCHNITT_ID INTEGER,
    ANZAHL            INTEGER,
    PRIMARY KEY (LAGERBESTAND_ID, LAGERABSCHNITT_ID),
    FOREIGN KEY (LAGERBESTAND_ID) REFERENCES LAGERBESTAND (LAGERBESTAND_ID),
    FOREIGN KEY (LAGERABSCHNITT_ID) REFERENCES LAGERABSCHNITT (LAGERABSCHNITT_ID)
);



CREATE TABLE ZUTAT
(
    ZUTAT_ID INTEGER,
    ZUTAT_NAME     Varchar2(20) UNIQUE NOT NULL,
    PRIMARY KEY (ZUTAT_ID)
);

CREATE TABLE BIERSORTE_ZUTAT
(
    BIERSORTE_ID INTEGER,
    ZUTAT_ID     INTEGER,
    MENGE        NUMBER(10, 4),
    EINHEIT      CHAR(4),
    Primary KEY (BIERSORTE_ID, ZUTAT_ID),
    FOREIGN KEY (BIERSORTE_ID) REFERENCES BIERSORTE (BIERSORTE_ID),
    FOREIGN KEY (ZUTAT_ID) REFERENCES ZUTAT (ZUTAT_ID)
);


